//! Rendering a composed page for an external system.
//!
//! Two jobs, both of which are about honesty rather than formatting:
//!
//! 1. **The banner.** Every published page says, at the top, that it is
//!    generated, when it was generated, and where to go to argue with it. A
//!    generated page that looks hand-written is a trap: the first person to
//!    "fix" it in Confluence will watch their edit vanish on the next compose and
//!    conclude the tool is hostile. Tell them before they type.
//!
//! 2. **Citations survive the trip.** The `[m:<uuid>]` markers are the whole
//!    provenance guarantee. Stripping them for tidiness would leave a page that
//!    reads like any other wiki page and can no longer be traced — which is
//!    precisely the thing we are selling against. They render as links back into
//!    the console, so a reader in Confluence is one click from the governed
//!    memory a named human signed.

use uuid::Uuid;

/// Where a reader goes to see the memory behind a claim.
pub fn memory_url(console_url: &str, memory_id: &Uuid) -> String {
    format!(
        "{}/memories/{}",
        console_url.trim_end_matches('/'),
        memory_id
    )
}

pub fn page_url(console_url: &str, slug: &str) -> String {
    format!("{}/docs/{}", console_url.trim_end_matches('/'), slug)
}

/// The generated-content banner, in markdown (the Git target's form).
pub fn banner_md(console_url: &str, slug: &str, published_at: &str) -> String {
    format!(
        "> **Generated by Brainiac — do not edit here.**\n\
         > This page is compiled from the organization's canonical memories and \
         is regenerated whenever they change; edits made in this tool will be \
         overwritten. Every claim links to the governed memory it came from.\n\
         > Last composed {published_at} · [open in Brainiac]({})\n\n",
        page_url(console_url, slug)
    )
}

/// When the circuit breaker has paused publishing, the live page must say so.
///
/// This is the whole point of the breaker being visible rather than silent: a
/// reader who knows the page is holding at Tuesday's version can go and check.
/// A reader who is not told simply believes a stale page.
pub fn stale_stamp_md(reason: &str, since: &str) -> String {
    format!(
        "> ⚠️ **Verification pending — this page is not being updated.**\n\
         > Brainiac paused publishing on {since} because {reason}. \
         What follows is the last version a human published; the organization's \
         knowledge may have moved on.\n\n"
    )
}

/// A one-line summary for machine-readable targets (OKF `description`): the
/// first body line that is prose — not a heading, list, quote, fence, or table
/// row — with citation markers stripped and truncated at a word boundary.
/// `None` when the page has no prose at all (e.g. a pure-diagram page); an
/// absent description is honest, a synthesized one is filler.
pub fn derive_description(content_md: &str) -> Option<String> {
    let mut in_code = false;
    for line in content_md.lines() {
        let t = line.trim();
        if t.starts_with("```") {
            in_code = !in_code;
            continue;
        }
        if in_code || t.is_empty() {
            continue;
        }
        if ['#', '>', '-', '*', '|', '<']
            .iter()
            .any(|c| t.starts_with(*c))
        {
            continue;
        }
        let cleaned = strip_citations(t);
        let cleaned = cleaned.trim();
        if cleaned.is_empty() {
            continue;
        }
        return Some(truncate_at_word(cleaned, 200));
    }
    None
}

/// Remove `[m:<uuid>]` markers — provenance belongs in structured fields, not
/// in a one-line summary.
fn strip_citations(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(i) = rest.find("[m:") {
        out.push_str(&rest[..i]);
        match rest[i..].find(']') {
            Some(j) => rest = &rest[i + j + 1..],
            None => {
                out.push_str(&rest[i..]);
                return out;
            }
        }
    }
    out.push_str(rest);
    // Collapse the double spaces stripping leaves behind.
    out.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn truncate_at_word(s: &str, max_chars: usize) -> String {
    if s.chars().count() <= max_chars {
        return s.to_string();
    }
    let mut out: String = s.chars().take(max_chars).collect();
    if let Some(i) = out.rfind(' ') {
        out.truncate(i);
    }
    out.push('…');
    out
}

/// Escape text for Confluence storage format (XHTML).
fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Markdown → Confluence storage format (the XHTML dialect its REST API takes).
///
/// Deliberately small and total: headings, paragraphs, bullet lists, fenced code
/// (as a `code` macro), blockquotes, and our citation markers. Anything it does
/// not recognize is escaped and emitted as a paragraph — an unrecognized
/// construct must degrade to visible text, NEVER to markup we did not intend.
/// The alternative (a general HTML pipeline) would mean model output could reach
/// a customer's wiki as live markup, which is a far larger thing to get wrong
/// than a mis-rendered table.
pub fn markdown_to_storage(md: &str, console_url: &str) -> String {
    let mut out = String::new();
    let mut in_code = false;
    let mut code_buf = String::new();
    let mut in_list = false;

    let close_list = |out: &mut String, in_list: &mut bool| {
        if *in_list {
            out.push_str("</ul>");
            *in_list = false;
        }
    };

    for line in md.lines() {
        let t = line.trim_end();

        if t.trim_start().starts_with("```") {
            if in_code {
                out.push_str(&format!(
                    "<ac:structured-macro ac:name=\"code\"><ac:plain-text-body><![CDATA[{}]]></ac:plain-text-body></ac:structured-macro>",
                    // CDATA cannot contain "]]>"; splitting it is the standard,
                    // and only, safe escape.
                    code_buf.replace("]]>", "]]]]><![CDATA[>")
                ));
                code_buf.clear();
                in_code = false;
            } else {
                close_list(&mut out, &mut in_list);
                in_code = true;
            }
            continue;
        }
        if in_code {
            code_buf.push_str(line);
            code_buf.push('\n');
            continue;
        }

        if t.trim().is_empty() {
            close_list(&mut out, &mut in_list);
            continue;
        }

        let body = |s: &str| inline_to_storage(s, console_url);

        if let Some(h) = t.strip_prefix("### ") {
            close_list(&mut out, &mut in_list);
            out.push_str(&format!("<h3>{}</h3>", body(h)));
        } else if let Some(h) = t.strip_prefix("## ") {
            close_list(&mut out, &mut in_list);
            out.push_str(&format!("<h2>{}</h2>", body(h)));
        } else if let Some(h) = t.strip_prefix("# ") {
            close_list(&mut out, &mut in_list);
            out.push_str(&format!("<h1>{}</h1>", body(h)));
        } else if let Some(q) = t.strip_prefix("> ") {
            close_list(&mut out, &mut in_list);
            out.push_str(&format!("<blockquote><p>{}</p></blockquote>", body(q)));
        } else if let Some(li) = t.trim_start().strip_prefix("- ") {
            if !in_list {
                out.push_str("<ul>");
                in_list = true;
            }
            out.push_str(&format!("<li>{}</li>", body(li)));
        } else {
            close_list(&mut out, &mut in_list);
            out.push_str(&format!("<p>{}</p>", body(t)));
        }
    }
    close_list(&mut out, &mut in_list);
    // An unterminated fence still emits its content — dropping the tail of a page
    // silently would be worse than a slightly ugly one.
    if in_code && !code_buf.is_empty() {
        out.push_str(&format!(
            "<ac:structured-macro ac:name=\"code\"><ac:plain-text-body><![CDATA[{}]]></ac:plain-text-body></ac:structured-macro>",
            code_buf.replace("]]>", "]]]]><![CDATA[>")
        ));
    }
    out
}

/// Inline pass: escape everything, then re-introduce ONLY the constructs we
/// generate ourselves — bold, and citation links. Escaping first is what makes
/// this safe: a model that emits `<script>` gets a visible `&lt;script&gt;`.
fn inline_to_storage(s: &str, console_url: &str) -> String {
    let mut out = esc(s);

    // Our own evidence footer, `<sub>[m:uuid]</sub>`, has already been escaped;
    // normalize it back to a plain citation so it does not read as literal tags.
    out = out.replace("&lt;sub&gt;", "").replace("&lt;/sub&gt;", "");

    // Citations → links into the console.
    let mut result = String::with_capacity(out.len());
    let mut rest = out.as_str();
    while let Some(i) = rest.find("[m:") {
        let (before, tail) = rest.split_at(i);
        result.push_str(before);
        let after = &tail[3..];
        match after.find(']') {
            Some(j) => {
                let raw = &after[..j];
                match raw.trim().parse::<Uuid>() {
                    Ok(id) => result.push_str(&format!(
                        "<a href=\"{}\">[source]</a>",
                        memory_url(console_url, &id)
                    )),
                    // Not a real citation — leave the text as it stood.
                    Err(_) => result.push_str(&format!("[m:{raw}]")),
                }
                rest = &after[j + 1..];
            }
            None => {
                result.push_str(&tail[..3]);
                rest = &tail[3..];
            }
        }
    }
    result.push_str(rest);

    // Bold (**x**) — the only emphasis our composer emits.
    let mut bolded = String::with_capacity(result.len());
    let mut chunks = result.split("**");
    if let Some(first) = chunks.next() {
        bolded.push_str(first);
    }
    let mut open = true;
    for c in chunks {
        bolded.push_str(if open { "<strong>" } else { "</strong>" });
        bolded.push_str(c);
        open = !open;
    }
    // An odd number of `**` would leave a dangling <strong>; close it.
    if !open {
        bolded.push_str("</strong>");
    }
    bolded
}

#[cfg(test)]
mod tests {
    use super::*;

    const CONSOLE: &str = "https://brainiac.example.com";

    #[test]
    fn html_in_model_output_cannot_become_markup() {
        // The property that matters most: nothing the model writes reaches a
        // customer's wiki as live markup.
        let out = markdown_to_storage("An <img src=x onerror=alert(1)> attack.", CONSOLE);
        assert!(!out.contains("<img"), "{out}");
        assert!(out.contains("&lt;img"));
    }

    #[test]
    fn citations_become_links_back_to_the_governed_memory() {
        let id = Uuid::new_v4();
        let out = markdown_to_storage(&format!("The cap is 30s [m:{id}]."), CONSOLE);
        assert!(out.contains(&format!("{CONSOLE}/memories/{id}")), "{out}");
        assert!(out.contains("[source]"));
    }

    #[test]
    fn a_bogus_citation_stays_text_rather_than_becoming_a_broken_link() {
        let out = markdown_to_storage("Something [m:not-a-uuid] here.", CONSOLE);
        assert!(out.contains("[m:not-a-uuid]"), "{out}");
        assert!(!out.contains("<a href"));
    }

    #[test]
    fn code_blocks_survive_verbatim_in_a_code_macro() {
        let out = markdown_to_storage("```yaml\nretry:\n  max: 30s\n```", CONSOLE);
        assert!(out.contains("ac:name=\"code\""), "{out}");
        assert!(out.contains("max: 30s"));
    }

    #[test]
    fn a_cdata_terminator_inside_code_cannot_escape_the_block() {
        let out = markdown_to_storage("```\nevil ]]> break\n```", CONSOLE);
        // The raw terminator must not appear unsplit — that would end the CDATA
        // section early and let the rest of the code render as markup.
        assert!(!out.contains("evil ]]> break"), "{out}");
        assert!(out.contains("]]]]><![CDATA[>"));
    }

    #[test]
    fn headings_lists_and_quotes_render() {
        let out = markdown_to_storage("# T\n\n- one\n- two\n\n> note", CONSOLE);
        assert!(out.contains("<h1>T</h1>"));
        assert!(out.contains("<ul><li>one</li><li>two</li></ul>"), "{out}");
        assert!(out.contains("<blockquote>"));
    }

    #[test]
    fn description_is_the_first_prose_line_without_citations() {
        let id = Uuid::new_v4();
        let md = format!(
            "# PSP Gateway\n\n> generated banner\n\n- a list item\n\nThe gateway caps retries at 30 seconds [m:{id}] and fails open.\n\nMore prose."
        );
        let d = derive_description(&md).expect("description");
        assert_eq!(d, "The gateway caps retries at 30 seconds and fails open.");
    }

    #[test]
    fn description_is_none_for_a_page_with_no_prose() {
        assert_eq!(
            derive_description("# Title\n\n```mermaid\ngraph LR\n```\n"),
            None
        );
    }

    #[test]
    fn description_truncates_at_a_word_boundary() {
        let long = format!("Start {} end.", "word ".repeat(60));
        let d = derive_description(&long).expect("description");
        assert!(d.chars().count() <= 201, "{d}");
        assert!(d.ends_with('…'), "{d}");
        assert!(!d.contains("end."), "{d}");
    }

    #[test]
    fn the_banner_tells_a_reader_not_to_edit_here() {
        let b = banner_md(CONSOLE, "psp-gateway", "2026-07-14");
        assert!(b.contains("do not edit here"));
        assert!(b.contains("/docs/psp-gateway"));
    }

    #[test]
    fn a_paused_page_says_it_is_paused() {
        let s = stale_stamp_md("the review queue has stalled", "2026-07-14");
        assert!(s.contains("Verification pending"));
        assert!(s.contains("stalled"));
    }
}
