SET statement_timeout='20s';
INSERT INTO memories (id, org_id, visibility, status, kind, content) VALUES
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','pattern','ChainSonar is read-only and paper-only: no wallet, no private keys, no signing, and no real orders ever. It only reads the chain and simulates trades on paper with a 1000 notional and 7-day paper positions.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','pattern','ChainSonar scores are confidence-tiered and capped so a signal never looks more certain than its data; unknown checks render neutral and are never faked, and backtests are labelled illustrative and out-of-sample.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','fact','The ChainSonar discovery pipeline runs a fixed resumable order (discover, seed, buyers, rollup, curate) with cursors checkpointed in the scan_checkpoints table so a run resumes where it stopped.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','fact','An insider in ChainSonar is DEFAULT_PUMP: an early buyer within the first 20 swaps or 3600 seconds of at least two tokens that each peaked 5x or more within 7 days; pumpMultiple of 5 deliberately yields fewer false insiders.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','fact','ChainSonar curation shells out to the local claude CLI running Sonnet to label wallets GENUINE_INSIDER, SNIPER_BOT, or LUCKY_NOISE; the verdict is an AI assessment not ground truth, is cached in curated_wallets, and its USD cost is metered.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','pitfall','ChainSonar backtest circularity guard: it excludes every wallet-token pair used to certify a wallet and replays only that wallet other fresh buys, priced 7 days out on GeckoTerminal, reported tiered not blended.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','fact','ChainSonar data providers split by job: GeckoTerminal gives pools and OHLCV with no wallet data, Dune gives wallet flows via five saved queries, Alchemy gives token early-transfers, and the local claude CLI does curation.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','pitfall','ChainSonar rate limits: an upstream throttle is a typed error not empty data. A 429 throws PolygonRateLimitedError, GtRateLimit, or DuneError and never collapses into an empty array, a null, or a fabricated value.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','fact','ChainSonar respects a Dune budget of 2500 credits per month by using getLatestResults instead of re-executing queries, caching results for 6 hours, guarding once per token, and tallying spend with addCredits.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','pitfall','ChainSonar DuckDB conventions: a single globalThis-cached connection that is HMR-safe and single-writer, safe BigInt coercion, no foreign keys, and idempotent DDL using ALTER TABLE ADD COLUMN IF NOT EXISTS migrations.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','pitfall','ChainSonar README drift: the README documents a nonexistent Ethereum ERC-20 safety desk with files like lib/eth.ts and lib/safety.ts, but the real app is the Polygon insider-wallet pipeline in context-map.json and lib/.'),
 (gen_random_uuid(),'73b2d27f-5c79-498b-b627-798132b05f04','org','canonical','howto','ChainSonar runs on bun with Next 16.2.10 App Router, React 19.2, Tailwind v4, TypeScript strict; AGENTS.md warns this is not the Next.js you know and to read node_modules/next/dist/docs before writing Next code.');
SELECT count(*) AS seeded FROM memories WHERE org_id='73b2d27f-5c79-498b-b627-798132b05f04';
