/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness probe; unauthenticated. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The document itself. Open (like `/health`) — a client needs the contract
         *     before it has a token, and the spec describes shapes, never data.
         * @description This OpenAPI document, derived from the handlers.
         */
        get: operations["openapi_json"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Governance health counters under the caller's RLS view: memories by status, review backlog, graph size, ingest queue depth. */
        get: operations["analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/observatory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The dashboard payload: status totals, weekly captured/promoted flow, kind×team volumes, top canonical themes, review latency, contradiction mix, queue depth. */
        get: operations["observatory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reverse-chronological feed of governance actions: promotion reviews
         *     (human and policy) and contradiction resolutions. Reuses the reviewer /
         *     resolved-by columns both tables already carry; rows resolve under the
         *     caller's RLS transaction so members see their org slice only.
         * @description Reverse-chronological feed of governance actions: promotion reviews (human and policy) and contradiction resolutions.
         */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The entity graph: canonical hubs, team-scoped surface entities, and evidence edges (bounded at 2000/2000/5000 rows). */
        get: operations["graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/canonical/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L2/L3: one canonical entity's neighborhood — surface forms per team,
         *     1-hop evidence edges (content RLS-scoped), neighbor canonicals reachable
         *     through those edges, and the anchored memories the caller may read.
         * @description Cortex map L2/L3: one canonical entity's neighborhood — surface forms per team, 1-hop evidence edges, neighbor canonicals, and readable anchored memories.
         */
        get: operations["graph_canonical"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * L0/L1: team lobes with volumes, top canonical hubs with team spread, and
         *     team-pair binding strength (shared canonicals). Bounded by construction.
         * @description Cortex map L0/L1: team lobes with volumes, the top 60 canonical hubs with their team spread, and team-pair binding strength.
         */
        get: operations["graph_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Browse the memory archive, optionally as-of an instant (time travel over the validity windows). Returns the filtered total alongside the page. */
        get: operations["memories_list"];
        put?: never;
        /** @description Ingest raw content as a source and enqueue the extraction pipeline (async). */
        post: operations["memory_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The re-verification queue: live candidate/canonical memories whose
         *     validity window closes within the horizon, oldest boundary first.
         * @description The re-verification queue: live candidate/canonical memories whose validity window closes within the horizon, oldest boundary first.
         */
        get: operations["memories_expiring"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Hybrid (vector + lexical + graph) retrieval under the caller's RLS scope. */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One memory with its provenance, anchored entities, promotion history, and supersession lineage (signed chain depth: negative = predecessors). */
        get: operations["memory_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/memories/{id}/feedback — report how a served memory held up.
         *     Mirrors MCP `memory_feedback` exactly: synonyms are canonicalized, an
         *     invisible memory is a plain 404 (no existence oracle), and the same store
         *     calls run under the caller's RLS.
         * @description Report how a retrieved memory held up: helpful (alias useful), wrong, or outdated (alias stale). Verdicts drive ranking and re-verification.
         */
        post: operations["memory_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/memories/{id}/provenance — trace a memory's evidence chain. Read
         *     scope. Invisible-under-RLS resolves to 404, the same as a nonexistent id
         *     (no existence oracle) — mirrors MCP `memory_provenance`.
         * @description Trace a memory's evidence chain for citation: who/what recorded it, the model, when, the originating source with a short excerpt, and the canonical entities it anchors.
         */
        get: operations["memory_provenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memories/{id}/reverify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-verification is a governance act: like promotion review, it requires
         *     a maintainer of the owning team (org-wide memories: any org principal
         *     with write scope).
         * @description Re-verify a memory: extend its validity window from now and close any open feedback claims against it. Requires a maintainer of the owning team.
         */
        post: operations["memory_reverify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/org/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Org directory for the key-mint picker (admin scope — it feeds token
         *     management). Users/teams carry no RLS; org scoping is explicit.
         * @description Org directory for the key-mint picker: every user in the caller's org with their team memberships and roles. Requires admin scope.
         */
        get: operations["org_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pipeline/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent pipeline runs — the worker's own audit trail, org-scoped by RLS.
         * @description Recent pipeline runs — the worker's own audit trail, newest first, org-scoped by RLS.
         */
        get: operations["pipeline_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dead-lettered jobs, most recent first (default limit 50). */
        get: operations["queue_dead_letters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue/dead-letters/{id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Move a dead-lettered job back onto its queue for another attempt. */
        post: operations["queue_requeue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Operator view of one queue: depth, in-flight, retry histogram, archive tallies. */
        get: operations["queue_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/contradictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The contradiction queue: oldest first (SLA aging), plus a status histogram that powers the queue's tabs. */
        get: operations["list_contradictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/contradictions/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolve an open contradiction by supersede (deprecates the loser), coexist, or dismiss. Supersede requires a maintainer of the losing memory's team. */
        post: operations["resolve_contradiction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memories carrying unresolved `wrong` / `outdated` claims from the agents
         *     and operators who were served them — most-disputed first. This is where
         *     MCP memory_feedback verdicts land for a human.
         * @description Memories carrying unresolved wrong/outdated claims from the agents and operators served them, most-disputed first.
         */
        get: operations["feedback_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/feedback/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer the open claims against a memory. The three answers are the three
         *     things a maintainer can actually mean:
         *       reverified — checked it, still true → extend its validity window
         *       deprecated — the reporters are right → end it now, drop it from retrieval
         *       dismissed  — the reports are noise → leave the memory as-is
         *     Whichever is chosen, every open claim on that memory closes with it.
         * @description Answer every open feedback claim against a memory: reverified (extend validity), deprecated (end it now), or dismissed (memory stands).
         */
        post: operations["resolve_feedback_claims"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Promotions awaiting human review (oldest first, max 100). */
        get: operations["pending_promotions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/promotions/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve a pending promotion: moves the memory to the promotion's target status. Requires a maintainer of the owning team. */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/promotions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reject a pending promotion: the memory is marked rejected. Requires a maintainer of the owning team. */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent sources with their pipeline rollup — the monitor's feed. Queue
         *     state joins outside RLS (queue schema is org-blind); org membership is
         *     proven by the RLS read of `sources` itself.
         * @description Recent ingest sources with their pipeline rollup (memories, promoted, pending review) and derived queue status.
         */
        get: operations["sources_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/sources/{id} — what happened to an async memory_add. Closes the
         *     loop on the 202: the source row (RLS-scoped), the queue job state, and
         *     what the pipeline produced from it.
         * @description Ingestion status of a source: queue job state plus what the pipeline produced.
         */
        get: operations["source_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/tokens — list the org's tokens (metadata only, never secrets).
         * @description List the org's API tokens (metadata only; secrets are never retrievable).
         */
        get: operations["list_tokens"];
        put?: never;
        /**
         * POST /v1/tokens — mint a token. The secret appears ONCE in this response;
         *     only its sha256 is stored. Requires the `admin` scope (env bootstrap
         *     tokens qualify), so read/write tokens cannot mint tokens.
         * @description Mint an API token; the plaintext secret is returned once and never again.
         */
        post: operations["create_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Blast radius: exactly what a key minted for this principal could read,
         *     computed by opening a transaction AS that principal — the same RLS path
         *     the runtime uses, so the preview can't drift from enforcement.
         * @description Blast-radius preview for a key minted for a given user: what that principal could read, computed under their own RLS. Requires admin scope.
         */
        post: operations["token_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/tokens/{id}/revoke — kill a token immediately.
         * @description Revoke a token immediately; subsequent requests with it are 401.
         */
        post: operations["revoke_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyticsGraph: {
            /** Format: int64 */
            canonicals: number;
            /** Format: int64 */
            entities: number;
        };
        AnalyticsResponse: {
            embedding_model: string;
            graph: components["schemas"]["AnalyticsGraph"];
            memories_by_status: components["schemas"]["StatusCount"][];
            queue: components["schemas"]["QueueDepth"];
            reviews: components["schemas"]["AnalyticsReviews"];
        };
        AnalyticsReviews: {
            /** Format: int64 */
            flagged_memories: number;
            /** Format: int64 */
            oldest_pending_secs: number;
            /** Format: int64 */
            open_contradictions: number;
            /** Format: int64 */
            pending_promotions: number;
        };
        /** @description A canonical entity anchoring a hit (id + name). */
        AnchorRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        AnchoredMemory: {
            content: string;
            /** Format: uuid */
            id: string;
            kind: string;
            status: string;
            team: string;
        };
        /** @description Archive tallies, kept nested under `archived` (not flattened). */
        ArchivedCounts: {
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            ok: number;
        };
        /** @description One bucket of the retry-attempt histogram over the ready jobs. */
        AttemptsBucket: {
            /** Format: int32 */
            attempts: number;
            /** Format: int64 */
            count: number;
        };
        /**
         * @description One governance action. `kind` is `promotion_review` |
         *     `contradiction_resolution`; `memory_b` is only set for contradictions.
         */
        AuditEvent: {
            /**
             * Format: uuid
             * @description Null for policy (auto) decisions — no human actor.
             */
            actor_id?: string | null;
            /** Format: date-time */
            at: string;
            detail?: string | null;
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: uuid */
            memory_b?: string | null;
            /** Format: uuid */
            memory_id: string;
            outcome: string;
        };
        AuditResponse: {
            events: components["schemas"]["AuditEvent"][];
        };
        CanonicalDetailResponse: {
            canonical: components["schemas"]["CanonicalSummary"];
            edges: components["schemas"]["CanonicalEdge"][];
            memories: components["schemas"]["AnchoredMemory"][];
            neighbors: components["schemas"]["NeighborCanonical"][];
            surface_forms: components["schemas"]["SurfaceForm"][];
        };
        /**
         * @description A 1-hop edge touching a surface form; `evidence` is null when the backing
         *     memory is invisible to the caller.
         */
        CanonicalEdge: {
            /** Format: uuid */
            dst: string;
            dst_name: string;
            evidence?: string | null;
            /** Format: uuid */
            memory_id?: string | null;
            relation: string;
            /** Format: uuid */
            src: string;
            src_name: string;
        };
        CanonicalSummary: {
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
            summary?: string | null;
        };
        /**
         * @description One link of the supersession lineage. `depth` is **signed**: negative for
         *     predecessors (walking back), positive for successors (walking forward).
         */
        ChainLink: {
            content: string;
            /** Format: int64 */
            depth: number;
            /** Format: uuid */
            id: string;
            status: string;
            valid_from?: string | null;
            valid_to?: string | null;
        };
        /**
         * @description One side of a contradiction. `content` is null when the memory is not
         *     visible to the caller under RLS (the row itself is org-scoped metadata).
         */
        ContradictionMemoryRef: {
            content?: string | null;
            /** Format: uuid */
            id: string;
        };
        ContradictionQueueResponse: {
            contradictions: components["schemas"]["ContradictionRow"][];
            /** @description Status histogram over ALL contradictions — unaffected by the filters. */
            counts: components["schemas"]["StatusCount"][];
        };
        ContradictionRow: {
            /** Format: int64 */
            age_secs: number;
            /** Format: date-time */
            created_at: string;
            detected_by: string;
            /** Format: uuid */
            id: string;
            memory_a: components["schemas"]["ContradictionMemoryRef"];
            memory_b: components["schemas"]["ContradictionMemoryRef"];
            /** Format: date-time */
            resolved_at?: string | null;
            /** Format: uuid */
            resolved_by?: string | null;
            status: string;
            /**
             * @description `contradictions.resolution_note` — the detector's suggestion, or the
             *     resolver's note once answered.
             */
            suggested_resolution?: string | null;
        };
        CreateTokenBody: {
            name: string;
            /** @description Subset of read|write|admin; defaults to ["read"]. */
            scopes?: string[] | null;
            /**
             * Format: uuid
             * @description Principal the token acts as; defaults to the caller.
             */
            user_id?: string | null;
        };
        /**
         * @description The mint response. `token` is the plaintext secret and is the only place
         *     it will ever appear — everything else is retrievable from `GET /v1/tokens`.
         */
        CreatedTokenResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            prefix: string;
            scopes: string[];
            /** @description Shown exactly once — never retrievable again. */
            token: string;
            /** Format: uuid */
            user_id: string;
        };
        /**
         * @description One dead-lettered job. `payload` is the opaque job JSON, passed through
         *     verbatim (its shape belongs to the pipeline, not to this API).
         */
        DeadLetterEntry: {
            /** Format: date-time */
            archived_at: string;
            /** Format: int32 */
            attempts: number;
            /** Format: date-time */
            enqueued_at: string;
            /** Format: int64 */
            id: number;
            payload: Record<string, never>;
        };
        DeadLetterListResponse: {
            dead_letters: components["schemas"]["DeadLetterEntry"][];
        };
        /**
         * @description The JSON error body. Documented once in the OpenAPI spec and returned by
         *     every error path.
         */
        ErrorResponse: {
            /**
             * @description Machine-readable slug:
             *     `bad_request` | `unauthorized` | `forbidden` | `not_found` |
             *     `payload_too_large` | `internal_error`.
             */
            code: string;
            /**
             * @description Human-readable message. Specific for business errors (400/401/403/404);
             *     a generic `"internal error"` for 5xx faults (detail is logged, not sent).
             */
            error: string;
        };
        /**
         * @description A memory in the re-verification horizon. `days_left` is computed per row
         *     against `now()` and is negative once the boundary has passed.
         */
        ExpiringMemory: {
            /** Format: float */
            confidence?: number | null;
            content: string;
            /** Format: int64 */
            days_left?: number | null;
            /** Format: uuid */
            id: string;
            kind: string;
            status: string;
            /** Format: uuid */
            team_id?: string | null;
            /** Format: date-time */
            valid_to?: string | null;
        };
        ExpiringResponse: {
            memories: components["schemas"]["ExpiringMemory"][];
            /** Format: int64 */
            window_days: number;
        };
        FeedbackBody: {
            /** @description Optional: what happened (especially for wrong/outdated). */
            note?: string | null;
            /** @description `helpful` (alias `useful`) | `wrong` | `outdated` (alias `stale`). */
            verdict: string;
        };
        /** @description Open claim counts against one memory. */
        FeedbackClaims: {
            /** Format: int64 */
            outdated: number;
            /** Format: int64 */
            wrong: number;
        };
        FeedbackQueueResponse: {
            flagged: components["schemas"]["FlaggedMemory"][];
        };
        /**
         * @description The receipt: the verdict as stored (after synonym canonicalization) plus
         *     the memory's running feedback totals.
         */
        FeedbackRecordedResponse: {
            feedback_totals: components["schemas"]["FeedbackVerdictCount"][];
            /** Format: uuid */
            memory_id: string;
            verdict: string;
        };
        /** @description One verdict tally for a memory. */
        FeedbackVerdictCount: {
            /** Format: int64 */
            count: number;
            verdict: string;
        };
        FlaggedMemory: {
            claims: components["schemas"]["FeedbackClaims"];
            content: string;
            kind: string;
            /** Format: uuid */
            memory_id: string;
            /** @description Reporter notes on the open claims (most recent first, capped). */
            notes: string[];
            /**
             * Format: int64
             * @description Age of the OLDEST open claim — how long the dispute has stood.
             */
            oldest_claim_secs: number;
            status: string;
            /** Format: uuid */
            team_id?: string | null;
            /** Format: date-time */
            valid_to?: string | null;
        };
        GraphCanonical: {
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
        };
        /**
         * @description An evidence edge. `evidence` is null when the backing memory is hidden by
         *     RLS — the edge itself stays visible (it's org metadata).
         */
        GraphEdge: {
            /** Format: uuid */
            dst: string;
            evidence?: string | null;
            /** Format: uuid */
            memory_id?: string | null;
            relation: string;
            /** Format: uuid */
            src: string;
        };
        GraphEntity: {
            /**
             * Format: uuid
             * @description Null when the entity has not been linked to a canonical hub yet.
             */
            canonical_id?: string | null;
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
            /** Format: uuid */
            team_id: string;
        };
        GraphOverviewResponse: {
            canonicals: components["schemas"]["OverviewCanonical"][];
            team_links: components["schemas"]["TeamLink"][];
            teams: components["schemas"]["TeamLobe"][];
        };
        GraphResponse: {
            canonicals: components["schemas"]["GraphCanonical"][];
            edges: components["schemas"]["GraphEdge"][];
            entities: components["schemas"]["GraphEntity"][];
        };
        /** @description Liveness probe body — `{"status":"ok"}` and nothing else. */
        HealthResponse: {
            status: string;
        };
        /**
         * @description An OPEN contradiction touching a hit (mirrors the MCP search `contradicts`
         *     entries, mcp.rs:557): the contradiction row and the memory it conflicts
         *     with. Reuses [`brainiac_store::governance::open_contradictions_for`].
         */
        HitContradiction: {
            /** Format: uuid */
            contradiction_id: string;
            /** Format: uuid */
            counterpart_id: string;
        };
        /**
         * @description What previous readers reported about a hit (mirrors the MCP search
         *     `feedback` block, mcp.rs:544). Present only when the memory carries any
         *     feedback at all — reuses [`brainiac_store::feedback::trust_for`].
         */
        HitFeedback: {
            /** @description True while an unresolved wrong/outdated claim stands — treat as unconfirmed. */
            disputed: boolean;
            /** Format: int64 */
            helpful: number;
            /** Format: int64 */
            outdated: number;
            /** Format: int64 */
            wrong: number;
        };
        KindTeamCount: {
            /** Format: int64 */
            count: number;
            kind: string;
            team: string;
        };
        /**
         * @description The 202 receipt: the source row that was written and the queue job that
         *     will extract memories from it. Poll `GET /v1/sources/{id}` with `source_id`.
         */
        MemoryAcceptedResponse: {
            /** Format: int64 */
            job_id: number;
            /** Format: uuid */
            source_id: string;
        };
        MemoryAddBody: {
            content: string;
            /** Format: uuid */
            team_id?: string | null;
        };
        MemoryChain: {
            predecessors: components["schemas"]["ChainLink"][];
            successors: components["schemas"]["ChainLink"][];
        };
        MemoryDetailResponse: {
            chain: components["schemas"]["MemoryChain"];
            entities: components["schemas"]["MemoryEntityRef"][];
            memory: components["schemas"]["MemoryRow"];
            promotions: components["schemas"]["MemoryPromotion"][];
            provenance?: null | components["schemas"]["MemoryProvenance"];
        };
        MemoryEntityRef: {
            kind: string;
            name: string;
            team: string;
        };
        MemoryListResponse: {
            memories: components["schemas"]["MemoryRow"][];
            /** Format: int64 */
            total: number;
        };
        /** @description A promotion attempt on this memory. Timestamps are RFC3339 strings here. */
        MemoryPromotion: {
            created_at?: string | null;
            from_status: string;
            policy_decision: string;
            policy_rule?: string | null;
            reviewed_at?: string | null;
            to_status: string;
        };
        /**
         * @description The provenance record behind a memory. The whole object is **null** (not
         *     omitted) when the memory has no provenance row.
         */
        MemoryProvenance: {
            actor_id: string;
            actor_kind: string;
            model_ref?: string | null;
            source_kind?: string | null;
            source_ref?: string | null;
        };
        /**
         * @description A memory's evidence chain for citation. Mirrors MCP `memory_provenance`
         *     exactly: actor/model/time, the originating source (bounded excerpt), and the
         *     canonical entities it anchors.
         */
        MemoryProvenanceResponse: {
            actor_kind?: string | null;
            actor_ref?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            entity_anchors: components["schemas"]["AnchorRef"][];
            /** Format: uuid */
            memory_id: string;
            model_ref?: string | null;
            source?: null | components["schemas"]["ProvenanceSource"];
        };
        /**
         * @description The archive's memory row. NOTE the timestamps here are **RFC3339
         *     strings**, not `DateTime` — this handler stringifies them (unlike the
         *     contradiction/audit/expiring payloads, which pass `DateTime` through).
         *     `created_at` is non-null in practice but is read as an optional column, so
         *     it stays `Option<String>` to keep the emitted shape identical.
         */
        MemoryRow: {
            /** Format: float */
            confidence?: number | null;
            content: string;
            created_at?: string | null;
            /** Format: uuid */
            id: string;
            kind: string;
            status: string;
            /** Format: uuid */
            superseded_by?: string | null;
            team: string;
            /** Format: uuid */
            team_id: string;
            valid_from?: string | null;
            valid_to?: string | null;
            visibility: string;
        };
        NeighborCanonical: {
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
            /** Format: int64 */
            shared_edges: number;
        };
        ObservatoryResponse: {
            by_kind: components["schemas"]["KindTeamCount"][];
            contradictions: components["schemas"]["StatusCount"][];
            embedding_model: string;
            queue: components["schemas"]["QueueDepth"];
            review: components["schemas"]["ObservatoryReview"];
            top_entities: components["schemas"]["TopEntity"][];
            totals: components["schemas"]["StatusCount"][];
            weekly: components["schemas"]["ObservatoryWeekly"];
        };
        ObservatoryReview: {
            /** Format: int64 */
            auto_promoted: number;
            /** Format: int64 */
            avg_latency_secs: number;
            /** Format: int64 */
            oldest_pending_secs: number;
            /** Format: int64 */
            pending: number;
            /** Format: int64 */
            reviewed: number;
        };
        ObservatoryWeekly: {
            captured: components["schemas"]["WeeklyPoint"][];
            promoted: components["schemas"]["WeeklyPoint"][];
        };
        OrgUser: {
            email: string;
            /** Format: uuid */
            id: string;
            /**
             * @description Raw `json_agg` output — an array of `{id, name, role}` (empty array,
             *     never null, when the user is on no team).
             */
            teams: components["schemas"]["OrgUserTeam"][];
        };
        /**
         * @description Documentation-only mirror of one element of `OrgUser::teams`. The value is
         *     produced by Postgres `json_agg(json_build_object('id','name','role'))` and
         *     is forwarded verbatim as `serde_json::Value` so the bytes cannot drift;
         *     this struct exists purely to give the schema its real shape.
         */
        OrgUserTeam: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description `team_members.role` — e.g. `member` | `maintainer`. */
            role: string;
        };
        OrgUsersResponse: {
            users: components["schemas"]["OrgUser"][];
        };
        /**
         * @description A canonical hub with its team spread. `teams` is the DISTINCT team count;
         *     `team_ids` is the set itself.
         */
        OverviewCanonical: {
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: int64 */
            memories: number;
            name: string;
            team_ids: string[];
            /** Format: int64 */
            teams: number;
        };
        PendingPromotion: {
            /** Format: int64 */
            age_secs: number;
            from_status: string;
            /** Format: uuid */
            id: string;
            memory?: null | components["schemas"]["PromotionMemory"];
            /** Format: uuid */
            memory_id: string;
            policy_rule?: string | null;
            provenance?: null | components["schemas"]["PromotionProvenance"];
            to_status: string;
        };
        /**
         * @description One worker run. `started_at` is an RFC3339 **string**; `duration_secs`
         *     measures against `now()` while the run is still open.
         */
        PipelineRunRow: {
            detail?: string | null;
            /** Format: int64 */
            duration_secs: number;
            /** Format: uuid */
            id: string;
            stage: string;
            started_at: string;
            status: string;
        };
        PipelineRunsResponse: {
            runs: components["schemas"]["PipelineRunRow"][];
        };
        PreviewBody: {
            /** Format: uuid */
            user_id: string;
        };
        /**
         * @description Memory body of a pending promotion. `None` on the parent ⇒ serialized as
         *     `null` (RLS-invisible memory) — never omitted.
         */
        PromotionMemory: {
            /** Format: float */
            confidence?: number | null;
            content: string;
            kind?: string | null;
            status?: string | null;
            team?: string | null;
        };
        /** @description Provenance of a pending promotion; `null` alongside an invisible memory. */
        PromotionProvenance: {
            actor_id: string;
            actor_kind: string;
            model_ref?: string | null;
            source_kind?: string | null;
            source_ref?: string | null;
        };
        PromotionQueueResponse: {
            promotions: components["schemas"]["PendingPromotion"][];
        };
        /**
         * @description The originating source, with a bounded excerpt of its raw text. `null` when
         *     the memory carries no source; `excerpt` is `null` when the source has no
         *     text.
         */
        ProvenanceSource: {
            /**
             * @description Bounded to SOURCE_EXCERPT_CHARS (500) chars — a citation handle, never
             *     the whole transcript.
             */
            excerpt?: string | null;
            kind: string;
        };
        /** @description Ingest queue depth — shared by `/v1/analytics` and the observatory. */
        QueueDepth: {
            /** Format: int64 */
            ingest_depth: number;
        };
        QueueHealthResponse: {
            archived: components["schemas"]["ArchivedCounts"];
            attempts_histogram: components["schemas"]["AttemptsBucket"][];
            /** Format: int64 */
            dead_letters: number;
            /** Format: int64 */
            in_flight: number;
            /** Format: int64 */
            oldest_ready_secs: number;
            queue: string;
            /** Format: int64 */
            ready: number;
        };
        /** @description Confirmation of a requeue; `requeued` is always `true` (a miss 404s). */
        RequeueResponse: {
            /** Format: int64 */
            id: number;
            requeued: boolean;
        };
        ResolveBody: {
            note?: string | null;
            /** @description supersede | coexist | dismiss */
            resolution: string;
            /**
             * Format: uuid
             * @description Required for supersede: the memory that wins.
             */
            winner_memory_id?: string | null;
        };
        /**
         * @description The contradiction's new terminal status (`resolved_supersede` |
         *     `resolved_coexist` | `dismissed`).
         */
        ResolveContradictionResponse: {
            /** Format: uuid */
            contradiction_id: string;
            status: string;
        };
        ResolveFeedbackBody: {
            /**
             * Format: int64
             * @description For `reverified`: the new validity budget (defaults to the kind TTL).
             */
            days?: number | null;
            /** @description reverified | deprecated | dismissed */
            resolution: string;
        };
        /**
         * @description `valid_to` is null for `deprecated`/`dismissed` (only `reverified` moves
         *     the boundary) — null, never absent.
         */
        ResolveFeedbackResponse: {
            /** Format: int64 */
            claims_closed: number;
            /** Format: uuid */
            memory_id: string;
            resolution: string;
            /** Format: date-time */
            valid_to?: string | null;
        };
        ReverifyBody: {
            /**
             * Format: int64
             * @description New validity budget from now; defaults to the kind's standard TTL.
             */
            days?: number | null;
        };
        ReverifyResponse: {
            /** Format: int64 */
            claims_closed: number;
            /**
             * Format: int64
             * @description The budget actually applied, after clamping.
             */
            days: number;
            /** Format: uuid */
            memory_id: string;
            reverified: boolean;
            /**
             * Format: date-time
             * @description The new validity boundary (never null on success).
             */
            valid_to: string;
        };
        /**
         * @description Outcome of an approve/reject: the promotion, the memory it moved, and the
         *     status that memory now carries.
         */
        ReviewDecisionResponse: {
            /** @description `approved` | `denied` */
            decision: string;
            /** Format: uuid */
            memory_id: string;
            /** @description The memory's status after the decision. */
            memory_status: string;
            /** Format: uuid */
            promotion_id: string;
        };
        /** @description Confirmation of a revoke; `revoked` is always `true` (a no-op revoke 404s). */
        RevokeResponse: {
            /** Format: uuid */
            id: string;
            revoked: boolean;
        };
        SearchBody: {
            /** Format: date-time */
            as_of?: string | null;
            k?: number;
            /** @description Memory kinds to keep (fact|decision|pattern|pitfall|howto); omit for all. */
            kinds?: string[];
            /**
             * Format: float
             * @description Minimum extractor confidence 0..1.
             */
            min_confidence?: number | null;
            /** @description Trust floor: raw|candidate|canonical (candidate ⇒ candidate+canonical). */
            min_status?: string | null;
            query: string;
            /**
             * Format: uuid
             * @description Restrict to one team's memories.
             */
            team_id?: string | null;
        };
        SearchHit: {
            /**
             * @description Canonical entities anchoring this hit; for via_graph hits, the bridge it
             *     surfaced through. Empty when the memory has no canonical-linked entities.
             */
            anchors: components["schemas"]["AnchorRef"][];
            content: string;
            /** @description Open contradictions this memory is part of — omitted when there are none. */
            contradictions?: components["schemas"]["HitContradiction"][];
            feedback?: null | components["schemas"]["HitFeedback"];
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: uuid */
            provenance_id?: string | null;
            /** Format: double */
            score: number;
            status: string;
            via_graph: boolean;
        };
        SearchResponse: {
            hits: components["schemas"]["SearchHit"][];
        };
        SourceFeedResponse: {
            sources: components["schemas"]["SourceRow"][];
        };
        /** @description The source row itself, as the caller's RLS scope sees it. */
        SourceInfo: {
            /** Format: date-time */
            created_at: string;
            external_ref?: string | null;
            kind: string;
        };
        /**
         * @description Queue state of the ingest job. `null` on the parent once the job has aged
         *     out of both `queue.jobs` and `queue.archive`.
         */
        SourceJob: {
            /** Format: int32 */
            attempts: number;
            /** @description Archive outcome (`ok` / failure reason); always null while queued. */
            outcome?: string | null;
            /** @description `queued` (still in `queue.jobs`) or `archived`. */
            state: string;
        };
        /** @description What the pipeline produced from this source (nested, not flattened). */
        SourceResults: {
            /** Format: int64 */
            memories: number;
            /** Format: int64 */
            pending_review: number;
            /** Format: int64 */
            promoted: number;
        };
        /**
         * @description A source with its pipeline rollup. `created_at` is an RFC3339 **string**
         *     here (this handler stringifies it). `status` is derived from the queue
         *     job + memory count: queued | retrying | processed | failed | unknown.
         */
        SourceRow: {
            /**
             * Format: int32
             * @description Queue delivery attempts; null when no queue job is known.
             */
            attempts?: number | null;
            created_at: string;
            external_ref?: string | null;
            /** Format: uuid */
            id: string;
            kind: string;
            /** Format: int64 */
            memories: number;
            /** Format: int64 */
            pending_review: number;
            /** Format: int64 */
            promoted: number;
            status: string;
            team?: string | null;
        };
        SourceStatusResponse: {
            job?: null | components["schemas"]["SourceJob"];
            results: components["schemas"]["SourceResults"];
            source: components["schemas"]["SourceInfo"];
            /** Format: uuid */
            source_id: string;
            /** @description One-word rollup: queued|retrying|processed|failed|unknown. */
            status: string;
        };
        /**
         * @description `{status, count}` — the shape every status histogram in this module emits
         *     (memories-by-status, contradiction tabs).
         */
        StatusCount: {
            /** Format: int64 */
            count: number;
            status: string;
        };
        /**
         * @description A team-scoped surface form linked into the canonical hub, with the link's
         *     confidence and resolution method.
         */
        SurfaceForm: {
            /** Format: float */
            confidence?: number | null;
            /** Format: uuid */
            entity_id: string;
            kind: string;
            method?: string | null;
            name: string;
            team: string;
            /** Format: uuid */
            team_id: string;
        };
        /** @description Binding strength between two team lobes = canonicals both teams link into. */
        TeamLink: {
            /** Format: uuid */
            a: string;
            /** Format: uuid */
            b: string;
            /** Format: int64 */
            shared: number;
        };
        /** @description A team lobe: the team plus its memory/entity volumes. */
        TeamLobe: {
            /** Format: int64 */
            entities: number;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            memories: number;
            name: string;
        };
        TokenListResponse: {
            tokens: components["schemas"]["TokenSummary"][];
        };
        TokenPreviewResponse: {
            email: string;
            /** @description Team names, not ids — this is the human-facing picker preview. */
            teams: string[];
            /** Format: uuid */
            user_id: string;
            visible: components["schemas"]["TokenVisibility"];
        };
        /** @description One token as the listing exposes it — metadata only, never the secret. */
        TokenSummary: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_used_at?: string | null;
            name: string;
            prefix: string;
            /** Format: date-time */
            revoked_at?: string | null;
            scopes: string[];
        };
        /** @description What a key minted for this principal could read, by visibility tier. */
        TokenVisibility: {
            /** Format: int64 */
            canonical: number;
            /** Format: int64 */
            org: number;
            /** Format: int64 */
            private: number;
            /** Format: int64 */
            team: number;
            /** Format: int64 */
            total: number;
        };
        TopEntity: {
            kind: string;
            /** Format: int64 */
            memories: number;
            name: string;
            /** Format: int64 */
            teams: number;
        };
        /**
         * @description One point of a weekly series; `week` is an ISO label (`IYYY-Www`) so the
         *     captured/promoted series stay joinable client-side.
         */
        WeeklyPoint: {
            /** Format: int64 */
            count: number;
            week: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    openapi_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Governance counters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
        };
    };
    observatory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Observatory dashboard payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservatoryResponse"];
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: {
                /** @description Max events (default 50, clamped 1..200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
        };
    };
    graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
        };
    };
    graph_canonical: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Canonical entity id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical neighborhood */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalDetailResponse"];
                };
            };
            /** @description Canonical entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    graph_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cortex overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOverviewResponse"];
                };
            };
        };
    };
    memories_list: {
        parameters: {
            query?: {
                /** @description Filter by memory kind */
                kind?: string;
                /** @description Filter by memory status */
                status?: string;
                /** @description Filter by owning team id */
                team?: string;
                /** @description RFC3339 instant: return rows VALID then, including since-deprecated ones */
                as_of?: string;
                /** @description Page size (default 50, clamped 1..200) */
                limit?: number;
                /** @description Page offset (default 0) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archive page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryListResponse"];
                };
            };
            /** @description as_of is not RFC3339 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memory_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryAddBody"];
            };
        };
        responses: {
            /** @description Source stored and job enqueued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryAcceptedResponse"];
                };
            };
            /** @description Empty content */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `write` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memories_expiring: {
        parameters: {
            query?: {
                /** @description Horizon in days (default 30, clamped 0..3650; 0 = only already-expired) */
                days?: number;
                /** @description Max rows (default 50) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expiring memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpiringResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchBody"];
            };
        };
        responses: {
            /** @description Ranked hits (k capped at 50) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Unknown kind/min_status, or min_confidence outside 0..=1 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `read` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memory_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDetailResponse"];
                };
            };
            /** @description Memory not found (or invisible under RLS) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memory_feedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory id you were served */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackBody"];
            };
        };
        responses: {
            /** @description Feedback recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRecordedResponse"];
                };
            };
            /** @description Unknown verdict, or an oversized note */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `write` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found (or invisible under RLS — no oracle) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memory_provenance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory id you were served */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provenance chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProvenanceResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `read` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found (or invisible under RLS — no oracle) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    memory_reverify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory id */
                id: string;
            };
            cookie?: never;
        };
        /** @description Optional validity budget; body may be omitted entirely */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverifyBody"];
            };
        };
        responses: {
            /** @description Memory re-verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverifyResponse"];
                };
            };
            /** @description Caller is not a maintainer of the owning team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found, or superseded (supersessions are final) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    org_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Org directory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgUsersResponse"];
                };
            };
        };
    };
    pipeline_runs: {
        parameters: {
            query?: {
                /** @description Max rows (default 30, clamped 1..200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent pipeline runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunsResponse"];
                };
            };
        };
    };
    queue_dead_letters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Queue name; defaults to the ingest queue. */
                queue: string | null;
                limit: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dead-letter listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeadLetterListResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `admin` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queue_requeue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Archive row id of the dead-lettered job */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequeueResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `admin` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job is not in the dead-letter archive */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queue_health: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Queue name; defaults to the ingest queue. */
                queue: string | null;
                limit: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue health snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueHealthResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `admin` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_contradictions: {
        parameters: {
            query?: {
                /** @description open | resolved_supersede | resolved_coexist | dismissed | all (default open) */
                status?: string;
                /** @description Filter by detector (e.g. embedding_similarity, llm) */
                detected_by?: string;
                /** @description Only rows at least this many hours old */
                min_age_hours?: number;
                /** @description Page size (default 50, clamped 1..200) */
                limit?: number;
                /** @description Page offset (default 0) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contradiction queue page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContradictionQueueResponse"];
                };
            };
            /** @description Unknown status filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolve_contradiction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contradiction id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveBody"];
            };
        };
        responses: {
            /** @description Contradiction resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveContradictionResponse"];
                };
            };
            /** @description Unknown resolution, or supersede without a valid winner_memory_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Supersede requires a maintainer of the losing memory's team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Contradiction not found / not open, or the losing memory is not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    feedback_queue: {
        parameters: {
            query?: {
                /** @description Max rows (default 50) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feedback triage queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackQueueResponse"];
                };
            };
        };
    };
    resolve_feedback_claims: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveFeedbackBody"];
            };
        };
        responses: {
            /** @description Claims closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveFeedbackResponse"];
                };
            };
            /** @description Unknown resolution */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Caller is not a maintainer of the owning team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found (or invisible under RLS) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pending_promotions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending review queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromotionQueueResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `read` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Promotion id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Promotion approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDecisionResponse"];
                };
            };
            /** @description Caller is not a maintainer of the owning team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Promotion not found or no longer pending */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Promotion id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Promotion rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDecisionResponse"];
                };
            };
            /** @description Caller is not a maintainer of the owning team */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Promotion not found or no longer pending */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sources_list: {
        parameters: {
            query?: {
                /** @description Max rows (default 30, clamped 1..100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFeedResponse"];
                };
            };
        };
    };
    source_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source id returned by POST /v1/memories */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatusResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `read` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source not found (or invisible under RLS — no oracle) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens of the caller's org */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenListResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `admin` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenBody"];
            };
        };
        responses: {
            /** @description Token minted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedTokenResponse"];
                };
            };
            /** @description Empty name or scopes outside read|write|admin */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `admin` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    token_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewBody"];
            };
        };
        responses: {
            /** @description Blast radius */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPreviewResponse"];
                };
            };
            /** @description User not found in this org */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token id (not the secret) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeResponse"];
                };
            };
            /** @description Missing or unknown bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token lacks the `admin` scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token not found or already revoked */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
